### PR TITLE
Update versioning

### PR DESCRIPTION
**Pull request by antoinemeyer5**
Change content of `version.txt`.

Change reading version way in `conf.py`

Create `cmake` folder.

Addition of a specific function in the `cmake` folder.

Use this function in the `CMakeLists.txt` file to obtain the PressioDemoapps version written in the version.txt file.

---

Change in `setup.cfg`. It adds a handwritten version because file `version.txt` can no longer be read directly.

### CODE REVIEW

**Comment by fnrizzi** [comment]
> adds a handwritten version because file version.txt can no longer be read directly.

why? are you saying that if we were to write inside `version.txt` just `0.14.0` it would work?

**Comment by antoinemeyer5** [comment]
> > adds a handwritten version because file version.txt can no longer be read directly.
> 
> why? are you saying that if we were to write inside `version.txt` just `0.14.0` it would work?

yes

**Comment by fnrizzi** [comment]
please keep `version.txt` as just:
```
0.14.0
```
i rather do this

**Comment by antoinemeyer5** [comment]
> please keep `version.txt` as just:
> 
> ```
> 0.14.0
> ```
> 
> i rather do this

Ok well it's almost like doing nothing

**Comment by fnrizzi** [comment]
> Ok well it's almost like doing nothing
what do you mean?

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
